// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace SqliteModels
{
    public partial class SqliteContextModel
    {
        partial void Initialize()
        {
            var accountSnapshot = AccountSnapshotEntityType.Create(this);
            var entityReference = EntityReferenceEntityType.Create(this);
            var budgetSnapshot = BudgetSnapshotEntityType.Create(this);
            var entityReference0 = EntityReference0EntityType.Create(this);
            var categoryMonthSnapshot = CategoryMonthSnapshotEntityType.Create(this);
            var entityReference1 = EntityReference1EntityType.Create(this);
            var categorySnapshot = CategorySnapshotEntityType.Create(this);
            var entityReference2 = EntityReference2EntityType.Create(this);
            var incomeCategorySnapshot = IncomeCategorySnapshotEntityType.Create(this);
            var entityReference3 = EntityReference3EntityType.Create(this);
            var masterCategorySnapshot = MasterCategorySnapshotEntityType.Create(this);
            var entityReference4 = EntityReference4EntityType.Create(this);
            var payeeSnapshot = PayeeSnapshotEntityType.Create(this);
            var entityReference5 = EntityReference5EntityType.Create(this);
            var subTransactionSnapshot = SubTransactionSnapshotEntityType.Create(this);
            var entityReference6 = EntityReference6EntityType.Create(this);
            var entityReference7 = EntityReference7EntityType.Create(this);
            var entityReference8 = EntityReference8EntityType.Create(this);
            var transactionSnapshot = TransactionSnapshotEntityType.Create(this);
            var entityReference9 = EntityReference9EntityType.Create(this);
            var entityReference10 = EntityReference10EntityType.Create(this);
            var entityReference11 = EntityReference11EntityType.Create(this);
            var entityReference12 = EntityReference12EntityType.Create(this);
            var info = InfoEntityType.Create(this);
            var sQLiteEvent = SQLiteEventEntityType.Create(this);

            EntityReferenceEntityType.CreateForeignKey1(entityReference, accountSnapshot);
            EntityReference0EntityType.CreateForeignKey1(entityReference0, budgetSnapshot);
            EntityReference1EntityType.CreateForeignKey1(entityReference1, categoryMonthSnapshot);
            EntityReference2EntityType.CreateForeignKey1(entityReference2, categorySnapshot);
            EntityReference3EntityType.CreateForeignKey1(entityReference3, incomeCategorySnapshot);
            EntityReference4EntityType.CreateForeignKey1(entityReference4, masterCategorySnapshot);
            EntityReference5EntityType.CreateForeignKey1(entityReference5, payeeSnapshot);
            EntityReference6EntityType.CreateForeignKey1(entityReference6, subTransactionSnapshot);
            EntityReference7EntityType.CreateForeignKey1(entityReference7, subTransactionSnapshot);
            EntityReference8EntityType.CreateForeignKey1(entityReference8, subTransactionSnapshot);
            EntityReference9EntityType.CreateForeignKey1(entityReference9, transactionSnapshot);
            EntityReference10EntityType.CreateForeignKey1(entityReference10, transactionSnapshot);
            EntityReference11EntityType.CreateForeignKey1(entityReference11, transactionSnapshot);
            EntityReference12EntityType.CreateForeignKey1(entityReference12, transactionSnapshot);

            AccountSnapshotEntityType.CreateAnnotations(accountSnapshot);
            EntityReferenceEntityType.CreateAnnotations(entityReference);
            BudgetSnapshotEntityType.CreateAnnotations(budgetSnapshot);
            EntityReference0EntityType.CreateAnnotations(entityReference0);
            CategoryMonthSnapshotEntityType.CreateAnnotations(categoryMonthSnapshot);
            EntityReference1EntityType.CreateAnnotations(entityReference1);
            CategorySnapshotEntityType.CreateAnnotations(categorySnapshot);
            EntityReference2EntityType.CreateAnnotations(entityReference2);
            IncomeCategorySnapshotEntityType.CreateAnnotations(incomeCategorySnapshot);
            EntityReference3EntityType.CreateAnnotations(entityReference3);
            MasterCategorySnapshotEntityType.CreateAnnotations(masterCategorySnapshot);
            EntityReference4EntityType.CreateAnnotations(entityReference4);
            PayeeSnapshotEntityType.CreateAnnotations(payeeSnapshot);
            EntityReference5EntityType.CreateAnnotations(entityReference5);
            SubTransactionSnapshotEntityType.CreateAnnotations(subTransactionSnapshot);
            EntityReference6EntityType.CreateAnnotations(entityReference6);
            EntityReference7EntityType.CreateAnnotations(entityReference7);
            EntityReference8EntityType.CreateAnnotations(entityReference8);
            TransactionSnapshotEntityType.CreateAnnotations(transactionSnapshot);
            EntityReference9EntityType.CreateAnnotations(entityReference9);
            EntityReference10EntityType.CreateAnnotations(entityReference10);
            EntityReference11EntityType.CreateAnnotations(entityReference11);
            EntityReference12EntityType.CreateAnnotations(entityReference12);
            InfoEntityType.CreateAnnotations(info);
            SQLiteEventEntityType.CreateAnnotations(sQLiteEvent);

            AddAnnotation("ProductVersion", "6.0.0");
        }
    }
}
