image: Visual Studio 2017
version: 0.1.0.{build}
configuration:
- Release
- Debug
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '0.1'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore src/OpenBudget.sln
build:
  project: src/OpenBudget.sln
  verbosity: minimal
artifacts:
  - path: src\OpenBudget.Presentation.Windows\bin
    name: WindowsBinaries