image: Visual Studio 2019
version: 0.1.0.{build}
configuration:
- Release
- Debug
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '0.1'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore src/OpenBudget.sln
build:
  project: src/OpenBudget.sln
  verbosity: minimal
after_build:
- cmd: dotnet publish src/OpenBudget.Presentation.Windows -r win-x64 --self-contained -c Release
artifacts:
  - path: src\OpenBudget.Presentation.Windows\bin\Release\net5.0-windows\win-x64\publish
    name: WindowsBinaries